target:
- target
continuous_cols:
- Max. conc. A
- IC50 A
- H A
- Einf A
- Max. conc. B
- IC50 B
- H B
- Einf B
categorical_cols:
- Cell line name
- Compound A
- Compound B
- GDSC tissue descriptor 2
- MSI
- Growth properties
- Putative target_A
- Function_A
- Pathway_A
- Putative target_B
- Function_B
- Pathway_B
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
task: regression
head: LinearHead
head_config:
  layers: ''
embedding_dims:
- - 85
  - 43
- - 55
  - 28
- - 48
  - 24
- - 12
  - 6
- - 4
  - 2
- - 4
  - 2
- - 46
  - 23
- - 7
  - 4
- - 14
  - 7
- - 40
  - 20
- - 7
  - 4
- - 14
  - 7
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.001
loss: MSELoss
metrics:
- mean_squared_error
metrics_prob_input:
- false
metrics_params:
- {}
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.category_embedding
_model_name: CategoryEmbeddingModel
_backbone_name: CategoryEmbeddingBackbone
_config_name: CategoryEmbeddingModelConfig
layers: 128-64-32
activation: ReLU
use_batch_norm: false
initialization: kaiming
dropout: 0.0
batch_size: 1024
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 100
min_epochs: 1
max_time: null
accelerator: gpu
devices: 1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 30
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: true
track_grad_norm: -1
progress_bar: rich
precision: 32
trainer_kwargs: {}
optimizer: Adam
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
categorical_dim: 12
continuous_dim: 8
output_dim: 1
categorical_cardinality:
- 85
- 55
- 48
- 12
- 4
- 4
- 46
- 7
- 14
- 40
- 7
- 14
embedded_cat_dim: 170
